### ISSUE TITLE
启用后目录显示两遍

### ISSUE THREAD

**Issue by klpek** [hongweipeng/MenuTree#1]
采用Matrial主题.
启用引入jQuery时,无法打开目.
当不启用时,有悬浮目录展示,但目录信息重复显示了两遍.
很好的工具,赞!
如果能做的更漂亮些就更好了

**Comment by hongweipeng** [comment]
@klpek 因为那个主题里调了两次 `content` . 在 `post.php`里面, 第一处 `<div class="mdl-card__media mdl-color-text--grey-50" style="background-image: url(<?php showThumbnail($this); ?>);">` 里面, `showThumbnail($this);` 函数里 `preg_match_all($pattern, $widget->content, $thumbUrl)` 隐式调用了.

第二处:`<?php $this->content(); ?>`

解决方法: 删除 ` style="background-image: url(<?php showThumbnail($this); ?>);"`  这个代码, 这部分好像没什么作用.

**Comment by klpek** [comment]
It's OK. Thank you.
