### ISSUE TITLE
可能是个人情况 CentOS7.7 宝塔 7.5.1 PHP7.3 typecho 1.2 (18.10.23) 启用这个插件后 php-fpm 出故障

### ISSUE THREAD

**Issue by hijoke** [hongweipeng/MenuTree#6]
启用这个插件后 php-fpm占用 CPU 会导致 vps 满载 网页内容除主页外无法打开
打开其他页面会白屏，vps 负载和 CPU 占用满载。
top 命令下多个 php-fpm 运行导致卡顿。
![image.png](https://p.pstatp.com/origin/fe500002e62105d814c0)
慢日志好像正常：
![image.png](https://p.pstatp.com/origin/1377f0001810352bd940d)
日志错误：
![image.png](https://p.pstatp.com/origin/138ba0000b039a30d7020)
多次重装网站和 php 发现问题。

**Comment by hongweipeng** [comment]
从调用的堆栈看是造成了递归调用了。堆栈里出现了和主题有关的函数，疑似插件与主题冲突了。

**Comment by hongweipeng** [comment]
已修复，与该主题冲突。

备注：该主题未使用jQuery，本插件需要jQuery依赖才能使用。
